p8105\_hw3\_rq2166
================
Ruoyuan Qian
10/8/2019

# Problem 1

## a)

**Description of `instacart`**

`The number of aisle and the most items ordered from the aisles:`

There are `134`aisles in it, and the most items are order from `fresh
vegetables`aisles in total.

The number of observation in `instacart` is `1384617`. And there are
`15` variables in it. Each row in the dataset is a product from an
order. There is a single order per user in this dataset. There are
`131209` unique users in it and there are `21` unique departments in it.

The key variables in `instacart` include information on order, including
the order sequence number(`order_number`) and the time of the
order(`order_dow`, `order_hour_of_day`), product(`product_name`),
aisle(`aisle`) and department(`department`).

**`For example`**

As for

<table>

<thead>

<tr>

<th style="text-align:right;">

user\_id

</th>

<th style="text-align:right;">

order\_number

</th>

<th style="text-align:right;">

order\_dow

</th>

<th style="text-align:right;">

order\_hour\_of\_day

</th>

<th style="text-align:left;">

product\_name

</th>

<th style="text-align:left;">

aisle

</th>

<th style="text-align:left;">

department

</th>

</tr>

</thead>

<tbody>

<tr>

<td style="text-align:right;">

112108

</td>

<td style="text-align:right;">

4

</td>

<td style="text-align:right;">

4

</td>

<td style="text-align:right;">

10

</td>

<td style="text-align:left;">

Bulgarian Yogurt

</td>

<td style="text-align:left;">

yogurt

</td>

<td style="text-align:left;">

dairy eggs

</td>

</tr>

</tbody>

</table>

The user’s id is No.`112108`, his or her `4`th ordering product is
`Bulgarian Yogurt`, the product belongs to `yogurt` aisle, `dairy eggs`
department, the time of the order is `10`o’clock, the `4`th day in a
week.

## b)

Make a plot shows the number of items ordered in each aisle.

``` r
instacart %>% 
  group_by(aisle) %>% 
  summarize(n = n()) %>% 
  filter(n > 10000) %>% 
ggplot(aes(x= aisle)) + 
  geom_bar(aes(weight=n)) +
  coord_flip()+
labs(
       x    = "Aisle",
       y    = "The number of items ordered in each aisle",
       title = "Plot 1 The number of items ordered in each aisle "
       )
```

![](p8105_hw3_rq2166_files/figure-gfm/unnamed-chunk-2-1.png)<!-- -->

There are `39` aisles with the number of items ordered larger than
10000, `fresh vegetables` , `fresh fruits` and `packaged vegetables
fruits` are the three most popular aisles over all, they are ordered
`150609`, `150473` and `78493`times, respectively. The average number of
items ordered in aisles in the plot is about`2.7281\times 10^{4}`.

## c)

Make a table showing the three most popular items in “baking
ingredients”, “dog food care”, and “packaged vegetables fruits”.

``` r
Three_most_popular = 
 instacart %>% 
  group_by(aisle,product_name) %>% 
  filter(aisle %in% c("baking ingredients", "dog food care",
                      "packaged vegetables fruits")
          ) %>% 
  summarize( "number_of_times" = n()) %>% 
  mutate(rank=rank(-number_of_times)) %>% 
  filter(rank %in% c(1,2,3)) %>% 
  arrange(aisle,rank) 

 Three_most_popular %>% 
  knitr::kable(caption = "Table 1  The three most popular items in baking ingredients, dog food care, and packaged vegetables fruits",
               format = "html") 
```

<table>

<caption>

Table 1 The three most popular items in baking ingredients, dog food
care, and packaged vegetables fruits

</caption>

<thead>

<tr>

<th style="text-align:left;">

aisle

</th>

<th style="text-align:left;">

product\_name

</th>

<th style="text-align:right;">

number\_of\_times

</th>

<th style="text-align:right;">

rank

</th>

</tr>

</thead>

<tbody>

<tr>

<td style="text-align:left;">

baking ingredients

</td>

<td style="text-align:left;">

Light Brown Sugar

</td>

<td style="text-align:right;">

499

</td>

<td style="text-align:right;">

1

</td>

</tr>

<tr>

<td style="text-align:left;">

baking ingredients

</td>

<td style="text-align:left;">

Pure Baking Soda

</td>

<td style="text-align:right;">

387

</td>

<td style="text-align:right;">

2

</td>

</tr>

<tr>

<td style="text-align:left;">

baking ingredients

</td>

<td style="text-align:left;">

Cane Sugar

</td>

<td style="text-align:right;">

336

</td>

<td style="text-align:right;">

3

</td>

</tr>

<tr>

<td style="text-align:left;">

dog food care

</td>

<td style="text-align:left;">

Snack Sticks Chicken & Rice Recipe Dog Treats

</td>

<td style="text-align:right;">

30

</td>

<td style="text-align:right;">

1

</td>

</tr>

<tr>

<td style="text-align:left;">

dog food care

</td>

<td style="text-align:left;">

Organix Chicken & Brown Rice Recipe

</td>

<td style="text-align:right;">

28

</td>

<td style="text-align:right;">

2

</td>

</tr>

<tr>

<td style="text-align:left;">

dog food care

</td>

<td style="text-align:left;">

Small Dog Biscuits

</td>

<td style="text-align:right;">

26

</td>

<td style="text-align:right;">

3

</td>

</tr>

<tr>

<td style="text-align:left;">

packaged vegetables fruits

</td>

<td style="text-align:left;">

Organic Baby Spinach

</td>

<td style="text-align:right;">

9784

</td>

<td style="text-align:right;">

1

</td>

</tr>

<tr>

<td style="text-align:left;">

packaged vegetables fruits

</td>

<td style="text-align:left;">

Organic Raspberries

</td>

<td style="text-align:right;">

5546

</td>

<td style="text-align:right;">

2

</td>

</tr>

<tr>

<td style="text-align:left;">

packaged vegetables fruits

</td>

<td style="text-align:left;">

Organic Blueberries

</td>

<td style="text-align:right;">

4966

</td>

<td style="text-align:right;">

3

</td>

</tr>

</tbody>

</table>

According to the Table 1, we can see the numbers of items ordered from
`packaged vegetables fruits` are much larger than others, the most
popular item in it is `packaged vegetables fruits` and its number of
ordered times is `9784`. The numbers of items ordered from `dog food
care` are the least one, the most popular item in it is `dog food care`
and its number of ordered times is `30`.

## d)

``` r
mean_hour = 
instacart %>% 
  group_by(product_name,order_dow) %>% 
  filter(product_name %in% c("Pink Lady Apples",
                             "Coffee Ice Cream")) %>%
  select(order_dow,order_hour_of_day,product_name)%>% 
  arrange(order_dow) %>% 
  mutate( mean = mean(order_hour_of_day),
          week = recode(order_dow, 
       "0"="Sunday",
       "1"="Monday",
       "2"="Tuesday",
       "3"="Wednesday",
       "4"="Thursday",
       "5"="Friday",
       "6"="Saturday")) %>% 
  ungroup(product_name,order_dow) %>%
  select(-order_hour_of_day,-order_dow) %>% 
      distinct() %>% 
  pivot_wider(
    names_from  = week, 
    values_from = mean
  ) 
mean_hour %>% 
  knitr::kable(caption = "Table 2  The mean hour of the day at which Pink Lady Apples and Coffee Ice Cream are ordered",
               format = "html")
```

<table>

<caption>

Table 2 The mean hour of the day at which Pink Lady Apples and Coffee
Ice Cream are ordered

</caption>

<thead>

<tr>

<th style="text-align:left;">

product\_name

</th>

<th style="text-align:right;">

Sunday

</th>

<th style="text-align:right;">

Monday

</th>

<th style="text-align:right;">

Tuesday

</th>

<th style="text-align:right;">

Wednesday

</th>

<th style="text-align:right;">

Thursday

</th>

<th style="text-align:right;">

Friday

</th>

<th style="text-align:right;">

Saturday

</th>

</tr>

</thead>

<tbody>

<tr>

<td style="text-align:left;">

Pink Lady Apples

</td>

<td style="text-align:right;">

13.44118

</td>

<td style="text-align:right;">

11.36000

</td>

<td style="text-align:right;">

11.70213

</td>

<td style="text-align:right;">

14.25000

</td>

<td style="text-align:right;">

11.55172

</td>

<td style="text-align:right;">

12.78431

</td>

<td style="text-align:right;">

11.93750

</td>

</tr>

<tr>

<td style="text-align:left;">

Coffee Ice Cream

</td>

<td style="text-align:right;">

13.77419

</td>

<td style="text-align:right;">

14.31579

</td>

<td style="text-align:right;">

15.38095

</td>

<td style="text-align:right;">

15.31818

</td>

<td style="text-align:right;">

15.21739

</td>

<td style="text-align:right;">

12.26316

</td>

<td style="text-align:right;">

13.83333

</td>

</tr>

</tbody>

</table>

According to the Table 2, the hours of purchasing `Pink Lady Apples` on
each day of the week is earlier than `Coffee Ice Cream`. The latest
ordered hour for `Pink Lady Apples` appears in `Wednesday`, and the
earliest ordered hour appears in `Monday`. The latest ordered hour for
`Coffee Ice Cream` appears in `Tuesday`, and the earliest ordered hour
appears in `Friday`.

# Problem 2

## Data cleaning

``` r
brfss = 
brfss_smart2010 %>% 
     janitor::clean_names()%>%
  filter(topic == "Overall Health"&
         response %in%
           c("Excellent","Very good",
             "Good","Fair","Poor")) %>% 
  mutate(response=factor(response, ordered=T,
          level=c("Poor","Fair","Good",
                  "Very good","Excellent"))) 
```

## a)

**2002**

There are `6` states( `CT, FL, MA, NC, NJ, PA`) observed at 7 or more
locations in 2002.

**2010**

There are `14` states (`CA, CO, FL, MA, MD, NC, NE, NJ, NY, OH, PA, SC,
TX, WA`) observed at 7 or more locations in 2010.

## b)

Limited the data to `"Excellent" response`

``` r
data_value_mean = brfss %>% 
  group_by(locationabbr,year) %>% 
  filter(response=="Excellent") %>% 
  mutate(mean = mean(data_value,na.rm=TRUE)) %>% 
  select(year,locationabbr,mean) %>% 
  distinct()
```

Make `“spaghetti”` plot of average value over time within a state

``` r
data_value_mean %>% 
  ggplot(aes(x=year, y=mean,color=locationabbr,group=locationabbr))+
  geom_line()+
  labs(
       x    = "Year",
       y    = "Average",
       title = "Plot 2  Spaghetti plot of avrage value over time within a state "
       )
```

![](p8105_hw3_rq2166_files/figure-gfm/unnamed-chunk-7-1.png)<!-- -->

According to the Plot2, there is a extreme decreasing trend for most of
the states in `2005`, especially for the `WV` state. Among all states,
`DC` state contained the highest mean value over the years while `WV`
state contained the lowest mean value over the years.

## c)

Distribution of `data_value` for responses among locations in NY State.

``` r
df =  brfss %>% 
  filter( locationabbr=="NY") %>% 
  select(year,locationdesc,data_value,response)
```

``` r
plot_2006_3 =
  df %>% 
  filter(year == 2006) %>% 
  group_by(response) %>% 
  mutate(mean_NY = mean(data_value,na.rm=TRUE)) %>% 
  ggplot(aes(x = data_value, fill = response)) + 
  geom_density(alpha = .4)+
  xlim(-1,46) +
  viridis::scale_color_viridis(
    discrete = TRUE
  )+
  labs(
       x    = "data_value",
       title = "Plot 3  Distribution of NY State in 2006"
       )

plot_2010_3 =
  df %>% 
  filter(year == 2010) %>% 
  group_by(response) %>% 
  mutate(mean_NY = mean(data_value,na.rm=TRUE)) %>% 
  ggplot(aes(x = data_value, fill = response)) + 
  geom_density(alpha = .4)+
  xlim(-1,46) +
  viridis::scale_color_viridis(
    discrete = TRUE
  )+
  labs(
       x    = "data_value",
       title = "Plot 4  Distribution of NY State in 2010"
       )

plot_2006_3/plot_2010_3
```

![](p8105_hw3_rq2166_files/figure-gfm/unnamed-chunk-9-1.png)<!-- -->
According to the Plot 3,

According to Plot 3 and 4, the distributions of `Poor` and `Excellent`
in 2006 were similar to the associated response in 2010, respectively.
And they almost remained in the same position among 2006 and 2010.
However, `Fair` became more dispersed compared to 2006, `Good` and `Very
good` were in opposite positions in the 2006 and 2010 distributions,
`Good` was less dispersed compared to 2006. Moreover, there was a trend
in 2010 by number from big to small: `Very good`, `Good`, `Excellent`,
`Fair` and then `Poor`.

# Problem 3

## a)

Tidy data

``` r
 accel_data = read_csv( "./data/accel_data.csv")%>%
  janitor::clean_names()%>%
  drop_na()%>%
  mutate(
    day = factor(day,ordered=T,
                  level=c("Sunday","Monday", 
                          "Tuesday","Wednesday", 
                          "Thursday", "Friday", 
                          "Saturday")),
     weekday_weekend =  case_when(
      as.numeric(day) < 6 ~ "Weekday",
      as.numeric(day) >= 6 ~ "Weekend",
      TRUE ~ ""
    )
  ) %>% 
  pivot_longer(
    activity_1:activity_1440,
    names_to = "activity",
    names_prefix = "activity_" ) %>% 
  mutate(
     activity = factor(activity,
                       level=c(1:1440),
                       ordered=T)) %>% 
  arrange(week,day)
```

    ## Parsed with column specification:
    ## cols(
    ##   .default = col_double(),
    ##   day = col_character()
    ## )

    ## See spec(...) for full column specifications.

**Description**

`accel_data`

The number of observation in `accel_data` is `50400`. And there are `6`
variables in it.

The variables in `accel_data` include information of time, including the
variables of week(`week`, `day_id`, `day`, `weekday_weekend`) and
information of activity(`activity`, `value`).

## b)

Table of total activity over the day

``` r
total_activity = 
 accel_data %>% 
  group_by(week,day) %>% 
  mutate(
    total = sum(value)  ) %>% 
  select(week,day,total) %>% 
  distinct() 

total_activity %>% 
  pivot_wider(names_from = "day",
              values_from = "total")%>% 
  knitr::kable(caption = "Table 3  Total activity for each day",format = "html")
```

<table>

<caption>

Table 3 Total activity for each day

</caption>

<thead>

<tr>

<th style="text-align:right;">

week

</th>

<th style="text-align:right;">

Sunday

</th>

<th style="text-align:right;">

Monday

</th>

<th style="text-align:right;">

Tuesday

</th>

<th style="text-align:right;">

Wednesday

</th>

<th style="text-align:right;">

Thursday

</th>

<th style="text-align:right;">

Friday

</th>

<th style="text-align:right;">

Saturday

</th>

</tr>

</thead>

<tbody>

<tr>

<td style="text-align:right;">

1

</td>

<td style="text-align:right;">

631105

</td>

<td style="text-align:right;">

78828.07

</td>

<td style="text-align:right;">

307094.2

</td>

<td style="text-align:right;">

340115

</td>

<td style="text-align:right;">

355923.6

</td>

<td style="text-align:right;">

480542.6

</td>

<td style="text-align:right;">

376254

</td>

</tr>

<tr>

<td style="text-align:right;">

2

</td>

<td style="text-align:right;">

422018

</td>

<td style="text-align:right;">

295431.00

</td>

<td style="text-align:right;">

423245.0

</td>

<td style="text-align:right;">

440962

</td>

<td style="text-align:right;">

474048.0

</td>

<td style="text-align:right;">

568839.0

</td>

<td style="text-align:right;">

607175

</td>

</tr>

<tr>

<td style="text-align:right;">

3

</td>

<td style="text-align:right;">

467052

</td>

<td style="text-align:right;">

685910.00

</td>

<td style="text-align:right;">

381507.0

</td>

<td style="text-align:right;">

468869

</td>

<td style="text-align:right;">

371230.0

</td>

<td style="text-align:right;">

467420.0

</td>

<td style="text-align:right;">

382928

</td>

</tr>

<tr>

<td style="text-align:right;">

4

</td>

<td style="text-align:right;">

260617

</td>

<td style="text-align:right;">

409450.00

</td>

<td style="text-align:right;">

319568.0

</td>

<td style="text-align:right;">

434460

</td>

<td style="text-align:right;">

340291.0

</td>

<td style="text-align:right;">

154049.0

</td>

<td style="text-align:right;">

1440

</td>

</tr>

<tr>

<td style="text-align:right;">

5

</td>

<td style="text-align:right;">

138421

</td>

<td style="text-align:right;">

389080.00

</td>

<td style="text-align:right;">

367824.0

</td>

<td style="text-align:right;">

445366

</td>

<td style="text-align:right;">

549658.0

</td>

<td style="text-align:right;">

620860.0

</td>

<td style="text-align:right;">

1440

</td>

</tr>

</tbody>

</table>

Plot of total activity over the day

``` r
total_activity %>%
  ungroup(week,day) %>% 
  mutate(id = c(1:length(total)))%>% 
  select(week,day,total)   %>%
  mutate(id = 1:length(day)) %>% 
  ggplot(aes(x=id,y=total,color=week))+
  geom_line()+
  labs(
       x    = "day",
       y    = "total activity each day",
       title = "Plot 5 Total activity over the day "
       )
```

![](p8105_hw3_rq2166_files/figure-gfm/unnamed-chunk-12-1.png)<!-- -->

It is hard to say the trend from the long table, and since the variable
`day_id` does not represent the order in which days were observed, I
created a new variable `id` which can represent the oder of the time.
And I drew an associated plot with `id` for `x axis` and `total
activity` for `y axis`. There is an increasing trend among the `first`
and `second` week and then a decreasing trend in `third` and `forth`
week. Besides, there are two equal minimums, which are `1440`, on the
`Saturday, Saturday`,week `4, 5`, respectively, and the maxium is
`6.8591\times 10^{5}`, it is on the `Monday`, week `3`.

## c)

``` r
 accel_data %>% 
  ggplot(aes(x= activity,y=value,
             color=day,group=day))+
  geom_line(alpha = .7)+
  viridis::scale_color_viridis(
   discrete = TRUE
  )+
 labs(
       x    = "Activity across 24 hours",
       y    = "Value",
       title = "Plot 6  24-hour activity time courses for each day "
       )
```

![](p8105_hw3_rq2166_files/figure-gfm/unnamed-chunk-13-1.png)<!-- -->

According to the Plot 6, there is a sharply drop among `“activity
counts”` in the midnight in all days, and there are about four peaks
in the plot, the first one appears early in the morning mostly
contributed by `Thursdays` and `Sundays`,`Wednesday`, the second one
appeared at noon, mostly contributed by `Sundays` and the third peak
appeared at the afternoon, contributed by `Saturdays` and `Sundays`, the
forth peak appeared in the evening, chontributed by `Fridays`,
`Wednesday` and `Saturdays`. Moreover, the `“activity counts”`on
`Mondays` and `Tuesdays` were flater than others. And the `“activity
counts”`on `Fridays` and `Sundays` were more fluctuating than others.
