---
title: "p8105_hw3_rq2166"
author: "Ruoyuan Qian"
date: "10/6/2019"
output: github_document
---

```{r setup, include=FALSE}
library(tidyverse)
library(ggplot2)
library(rnoaa)
library(ggridges)
library(p8105.datasets) 
#install.packages("devtools")
devtools::install_github("p8105/p8105.datasets")
library(p8105.datasets)
data("brfss_smart2010")
data("accel_data")

#install.packages("kableExtra")
library(kableExtra)
data("instacart")
library(ggridges)
devtools::install_github("thomasp85/patchwork")
library(patchwork)
```
# Problem 1
```{r}
instacart %>% 
  group_by(aisle) %>% 
  summarize(n = n()) %>% 
  pull(n) %>% 
  length()

instacart %>% 
  group_by(aisle) %>% 
  summarize(n = n()) %>% 
  filter(n == max(n))


  
instacart %>% 
  group_by(aisle) %>% 
  summarize(n = n()) %>% 
  filter(n > 10000) %>% 
ggplot(aes(x= aisle)) + 
  geom_bar(aes(weight=n)) + 
  coord_flip()
```
aisle ==  &
          aisle ==  
```{r}

instacart %>% 
  group_by(aisle,product_name) %>% 
  filter(aisle %in% c("baking ingredients", "dog food care",
                      "packaged vegetables fruits")
          ) %>% 
  summarize( n = n()) %>% 
  mutate(rank=rank(-n)) %>% 
  filter(rank %in% c(1,2,3)) %>% 
  ungroup(aisle,product_name) %>% 
  select(-aisle,-rank) %>% 
  pivot_wider(
    names_from  = product_name, 
    values_from = n
  ) %>% 
  knitr::kable(caption = "Table 1  The three most popular items in baking ingredients, dog food care, and packaged vegetables fruits",format = "html") 
  #add_header_abov(c("baking ingredients" = 3,"dog food care" = 3, "packaged vegetables fruits" = 3))

```
```{r}
instacart %>% 
  group_by(product_name,order_dow) %>% 
  filter(product_name %in% c("Pink Lady Apples",
                             "Coffee Ice Cream")) %>%
  select(order_dow,order_hour_of_day,product_name)%>% 
  mutate( mean = mean(order_hour_of_day),
          week = recode(order_dow, 
       "0"="Sunday",
       "1"="Monday",
       "2"="Tuesday",
       "3"="Wednesday",
       "4"="Thursday",
       "5"="Friday",
       "6"="Saturday")) %>% 
  ungroup(product_name,order_dow) %>%
  select(-order_hour_of_day,-order_dow) %>% 
      distinct() %>% 
  pivot_wider(
    names_from  = week, 
    values_from = mean
  ) %>% 
  knitr::kable(caption = "Table 2  The mean hour of the day at which Pink Lady Apples and Coffee Ice Cream are ordered",
               format = "html")
 
  
  
```

# Problem 2
```{r}
brfss = 
brfss_smart2010 %>% 
     janitor::clean_names()%>%
  filter(topic == "Overall Health",
         response %in%
           c("Excellent","Very good",
             "Good","Fair","Poor")) %>% 
  mutate(response=factor(response, ordered=T,
          level=c("Poor","Fair","Good","Very good","Excellent"
             ))) 

brfss%>% 
  filter(year==2002) %>% 
  group_by(locationabbr) %>% 
  summarize(n = n()) %>% 
  filter(n  >= 7)

brfss%>% 
  filter(year==2010) %>% 
  group_by(locationabbr) %>% 
  summarize(n = n()) %>% 
  filter(n  >= 7)

```

```{r}
data_value_mean = brfss %>% 
  group_by(locationabbr,year) %>% 
  filter(response=="Excellent") %>% 
  mutate(mean = mean(data_value,na.rm=TRUE)) %>% 
  select(year,locationabbr,mean) %>% 
  distinct()

data_value_mean %>% 
  ggplot(aes(x=year, y=mean,color=locationabbr))+
  geom_line()+
labs(
       x    = "Activity across 24 hours",
       y    = "Value",
       title = "Plot 1  Spaghetti plot of avrage value over time within a state "
       )

```

```{r}
df =  brfss %>% 
  filter( locationabbr=="NY") %>% 
  select(year,locationdesc,data_value,response)


plot_2006_1 = df %>% 
  filter(year == 2006) %>% 
  ggplot(aes(x =factor(locationdesc) ,y = data_value ,fill = response))+ geom_bar(stat = 'identity', position = 'dodge') + 
   coord_flip()+
labs(
       x    = "Location",
       y    = "data_value",
       title = "Plot 2  Distribution of NY State in 2006"
       )

plot_2006_2 = df %>% 
    filter(year == 2006) %>% 
ggplot(aes(x =factor(locationdesc) ,y = data_value ,fill = response))+ 
  geom_bar(stat = 'identity', position = 'stack') +
  guides(fill = guide_legend(reverse= T))+ 
   coord_flip()+
labs(
       x    = "Location",
       y    = "data_value",
       title = "Plot 2  Distribution of NY State in 2006"
       )


plot_2010_1 = df %>% 
  filter(year == 2010) %>% 
  ggplot(aes(x =factor(locationdesc) ,y = data_value ,fill = response))+ geom_bar(stat = 'identity', position = 'dodge') + 
   coord_flip()+
labs(
       x    = "Location",
       y    = "data_value",
       title = "Plot 3  Distribution of NY State in 2010"
       )

plot_2010_2 = df %>% 
    filter(year == 2010) %>% 
ggplot(aes(x =factor(locationdesc) ,y = data_value ,fill = response))+ 
  geom_bar(stat = 'identity', position = 'stack') +
  guides(fill = guide_legend(reverse= T))+ 
   coord_flip()+
labs(
       x    = "Location",
       y    = "data_value",
       title = "Plot 3  Distribution of NY State in 2010"
       )

plot_2006_1/plot_2010_1
plot_2006_2/plot_2010_2

```

```{r}
 accel_data = read_csv( "./data/accel_data.csv")%>%
  janitor::clean_names()%>%
  drop_na()%>%
  mutate(
    day = factor(day,ordered=T,
                  level=c("Monday", "Tuesday",
                          "Wednesday", 
                          "Thursday", "Friday", 
                          "Saturday", "Sunday")),
     weekday_weekend =  case_when(
      as.numeric(day) < 6 ~ "Weekday",
      as.numeric(day) >= 6 ~ "Weekend",
      TRUE ~ ""
    )
  ) %>% 
  pivot_longer(
    activity_1:activity_1440,
    names_to = "activity",
    names_prefix = "activity_" ) %>% 
  mutate(
    activity= as.numeric(activity)
  )


```

```{r}
 accel_data %>% 
  group_by(week,day_id) %>% 
  mutate(
    total = sum(value)
  ) %>% 
  select(week,day_id,total) %>% 
  distinct() %>% 
  knitr::kable(caption = "Table 3  Total activity for each day",format = "html")
```

```{r}
 accel_data %>% 
  mutate(day_id=as.character(day_id)) %>% 
  ggplot(aes(x= activity,y=value,
             color=day,group=day_id))+
  geom_smooth(se=F)+
  viridis::scale_color_viridis(
    discrete = TRUE
  )+
labs(
       x    = "Activity across 24 hours",
       y    = "Value",
       title = "Plot 4  24-hour activity time courses for each day "
       )


```

